export const CAMPUS_INTERESTS = [
  // cspell:disable
  "Basketball",
  "Tennis",
  "Table Tennis",
  "Badminton",
  "Running",
  "Cycling",
  "Swimming",
  "Martial Arts",
  "Boxing",
  "Yoga",
  "Meditation",
  "Hiking",
  "Traveling",
  "Road Trips",
  "Backpacking",
  "Foodie Adventures",
  "Cooking",
  "Baking",
  "Street Food",
  "Fine Dining",
  "Coffee Dates",
  "Tea Lover",
  "Brunch",
  "Nightlife",
  "Clubbing",
  "Karaoke",
  "Live Music",
  "Concerts",
  "Festivals",
  "DJing",
  "Music Production",
  "R&B",
  "Hip Hop",
  "Amapiano",
  "Jazz",
  "Classical Music",
  "K-Pop",
  "Podcasts",
  "Blogging",
  "Vlogging",
  "YouTube",
  "TikTok",
  "Streaming",
  "Esports",
  "Game Development",
  "UI/UX Design",
  "Graphic Design",
  "Video Editing",
  "3D Modeling",
  "AI & Machine Learning",
  "Data Science",
  "Hackathons",
  "Open Source",
  "Mobile Apps",
  "Startups",
  "Investing",
  "Side Hustles",
  "E-commerce",
  "Public Speaking",
  "Debating",
  "Volunteering",
  "Charity Work",
  "Community Building",
  "Spirituality",
  "Self Development",
  "Reading",
  "Writing",
  "Poetry",
  "Journaling",
  "Philosophy",
  "Psychology",
  "History",
  "Documentaries",
  "Sci-Fi",
  "Fantasy",
  "Romance Movies",
  "Thrillers",
  "True Crime",
  "Stand-up Comedy",
  "Memes",
  "Board Games",
  "Card Games",
  "Trivia",
  "Escape Rooms",
  "Bowling",
  "Skating",
  "Fashion Design",
  "Sneaker Culture",
  "Thrifting",
  "Luxury Lifestyle",
  "Minimalism",
  "Interior Design",
  "Architecture",
  "Cars",
  "Motorbikes",
  "Tech Gadgets",
  "Photography Editing",
  "Nature",
  "Sunsets",
  "Beach Days",
  "Picnics",
  "Pet Lovers",
  "Dogs",
  "Cats",
  "Exotic Pets",
  "Language Learning",
  "Cultural Exchange",
  "Study Abroad",
  "Networking",
  "Mentorship",
] as const;
