export interface CityConfig {
  id: string;
  name: string;
  neighborhoods: string[];
  allowsCustomInput?: boolean;
}

// cspell:disable
export const UNIVERSITY_LOCATIONS: Record<string, CityConfig[]> = {
  uniben: [
    {
      id: "benin-city",
      name: "Benin City (Oredo/Egor/Ikpoba-Okha)",
      neighborhoods: [
        "Ugbowo",
        "Ekosodin",
        "BDPA",
        "Isihor",
        "Oluku",
        "Uselu",
        "New Benin",
        "GRA",
        "Adesuwa",
        "Sapele Road",
        "Airport Road",
        "Ring Road",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "auchi",
      name: "Auchi & Environs",
      neighborhoods: ["Auchi Town", "South Ibie", "Jattu", "Iyekhei", "Other"],
      allowsCustomInput: true,
    },
    {
      id: "ekpoma",
      name: "Ekpoma (Esan West)",
      neighborhoods: [
        "Ujoelen",
        "Ihumudumu",
        "Iruekpen",
        "Emaudo",
        "Ujemen",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "uromi",
      name: "Uromi / Esan Central",
      neighborhoods: ["Uromi Town", "Irrua", "Other"],
      allowsCustomInput: true,
    },
    {
      id: "okada",
      name: "Okada (Ovia North-East)",
      neighborhoods: ["Okada Town", "Iguobazuwa", "Other"],
      allowsCustomInput: true,
    },
  ],
  unilag: [
    {
      id: "lagos-mainland-central",
      name: "Mainland Central (Yaba/Surulere)",
      neighborhoods: [
        "Akoka",
        "Yaba",
        "Onike",
        "Iwaya",
        "Abule Oja",
        "Bariga",
        "Shomolu",
        "Fadeyi",
        "Surulere",
        "Ebute Metta",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "ikeja-environs",
      name: "Ikeja & Alimosho",
      neighborhoods: [
        "Ikeja",
        "Maryland",
        "Ogba",
        "Agege",
        "Egbeda",
        "Ipaja",
        "Ikotun",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "lagos-island-lekki",
      name: "Island / Lekki / Ajah",
      neighborhoods: [
        "Lagos Island",
        "Victoria Island",
        "Ikoyi",
        "Lekki Phase 1",
        "Chevron",
        "Ajah",
        "Sangotedo",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "ikorodu-epe",
      name: "Ikorodu / Epe Axis",
      neighborhoods: [
        "Ikorodu Central",
        "Agric",
        "Benson",
        "Epe Town",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "ojo-badagry",
      name: "Ojo / Badagry Axis",
      neighborhoods: [
        "Ojo",
        "Festac",
        "Mile 2",
        "Okokomaiko",
        "Badagry Town",
        "Other",
      ],
      allowsCustomInput: true,
    },
  ],
  ui: [
    {
      id: "ibadan-north",
      name: "Ibadan North (UI Axis)",
      neighborhoods: [
        "Agbowo",
        "Bodija",
        "Samonda",
        "Orogun",
        "Ajibode",
        "Sango",
        "Mokola",
        "Ojoo",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "ibadan-central-south",
      name: "Ibadan Central & South",
      neighborhoods: [
        "Ring Road",
        "Challenge",
        "Dugbe",
        "Iyaganku",
        "Apata",
        "Akobo",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "ogbomosho",
      name: "Ogbomosho",
      neighborhoods: ["Ogbomosho North", "Ogbomosho South", "Other"],
      allowsCustomInput: true,
    },
    {
      id: "oyo-town",
      name: "Oyo Town / Iseyin",
      neighborhoods: ["Oyo East", "Oyo West", "Iseyin Town", "Other"],
      allowsCustomInput: true,
    },
  ],
  oau: [
    {
      id: "ile-ife",
      name: "Ile-Ife",
      neighborhoods: [
        "Lagere",
        "Mayfair",
        "Asherifa",
        "Parakin",
        "Ede Road",
        "Modakeke",
        "AP",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "osogbo",
      name: "Osogbo (Capital)",
      neighborhoods: [
        "Ogo-Oluwa",
        "Alekuwodo",
        "Dada Estate",
        "Oke-Fia",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "ede-ilesa",
      name: "Ede / Ilesa Axis",
      neighborhoods: ["Ede Town", "Ilesa West", "Ilesa East", "Other"],
      allowsCustomInput: true,
    },
  ],
  unn: [
    {
      id: "nsukka",
      name: "Nsukka & Environs",
      neighborhoods: [
        "Hilltop",
        "Odim",
        "Enugu Road",
        "Onuiyi",
        "Obeachara",
        "Ugwuaru",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "enugu-city",
      name: "Enugu Metropolis",
      neighborhoods: [
        "Independence Layout",
        "New Haven",
        "Abakpa",
        "Achara Layout",
        "GRA",
        "Trans Ekulu",
        "Ogui",
        "Other",
      ],
      allowsCustomInput: true,
    },
    {
      id: "agbani-awgu",
      name: "Agbani / Awgu Axis",
      neighborhoods: ["Agbani Town", "Awgu Town", "Udi", "Other"],
      allowsCustomInput: true,
    },
  ],
};
